export type Scenario = {
  id: string;
  name: string;
  description: string;
  demand: {
    'last-2025': boolean;
    'e100-pkw': boolean;
    'e100-pkw-million-km': number;
    'e100-heiz': boolean;
    'e100-heiz-target-heat-twh': number;
    'e100-lkw': boolean;
    'e100-lkw-target-bn-km': number;
    'e100-bahn': boolean;
    'e100-bahn-target-twh': number;
    'e100-schiff': boolean;
    'e100-schiff-target-twh': number;
    'e100-flug': boolean;
    'e100-flug-target-twh': number;
    'e100-ghd': boolean;
    'e100-ghd-target-heat-twh': number;
    'e100-industrie-waerme': boolean;
    'e100-industrie-waerme-target-heat-twh': number;
    'e100-stahl': boolean;
    'e100-stahl-target-mio-ton': number;
    'e100-chemie': boolean;
    'e100-chemie-target-twh': number;
  };
  renewables: { pvGW: number; windOnGW: number; windOffGW: number };
  fossil: { coalGW: number; gasGW: number };
  storage: { batteryPowerGW: number; batteryEnergyGWh: number; h2PowerGW: number; h2EnergyGWh: number; importLimitGW: number };
};
